### ISSUE TITLE
Сборка ОС

### ISSUE THREAD

**Issue by ivan770** [PROPHESSOR/JsOS#34]
Собственно, для разработки необходимо приложение закинуть в папку apps? Готово.
Далее, для запуска ОС необходимо сделать ISO. Вот здесь как раз возникла проблема. 
Винда выдаёт мне:
`D:\linux\JsOS-master>jsos mkiso error: Windows isn't supported platform`
А линукс в свою очередь:
`ivan770@Ivan770PC:/mnt/d/linux/JsOS-master$ jsos mkiso
Let's start to create the ISO image =)
 --- creating image ---
error: grub-mkrescue is not installed (or cannot be found)`

Как быть?

**Comment by imachug** [comment]
У меня заработало просто `jsos start`.

**Comment by PROPHESSOR** [comment]
Ну да, просто jsos start...
iso собирается только для запуска на реальной машине

**Comment by PROPHESSOR** [comment]
А для создания iso нужен grub-mkrescue

**Comment by usernameak** [comment]
Самая магическая штука тут - сборка ядра с нуля вместо использования готового блоба. Это могу только я.

**Comment by PROPHESSOR** [comment]
@usernameak и я)
