### ISSUE TITLE
undefined в консоли

### ISSUE THREAD

**Issue by dmitryyacenko** [PROPHESSOR/JsOS#35]
При пустом текущем вводе если нажать cmd(вроде бы WinKey на win/linux тоже прокатывает) в консоли появляется n(на самом деле undefined, но отображается только один символ), затем если нажать любую кнопку то выведется %нажатый_символ%ndefined, u так и остается левее(?)

**Comment by PROPHESSOR** [comment]
Спасибо, добавил в список багов

**Comment by PROPHESSOR** [comment]
[Исправлено](https://github.com/PROPHESSOR/JsOS/commit/78f8d6257e6385904b0fee42e6dea9d649d321bc)
